### PR TITLE
[WIP] Adding reserve contracts

### PR DESCRIPTION
**Pull request by nanspro**
Related Issue: https://github.com/GoodDollar/GoodHacking/issues/5

- [x] Add Bonding Curve for GoodDollar
- [x] Add GDX token to discourage selling G$
- [x] Add Reserve for ETH
- [ ] Add Reserve for ERC20 Tokens
- [ ] Write Test Cases

Note: The implementation is done for 3 tasks but still needs some debugging to make them work.

### CODE REVIEW

**Comment by nanspro** [comment]
@sirpy i am facing some issue with inheriting from GoodReserve and AccessReserve. I have to figure out how to use two ERC20 tokens in one contract, as of now it gives me error `Base constructor arguments given twice`.

**Comment by sirpy** [comment]
@nanspro GoodReserve and AccessReserve probably shouldn't be an ERC20 token.
they should receive in their constructor the ERC20 tokens they are going to work with.
ie GoodResrve(ERC20 _gooddollar, ERC20 _gooddollarx)

**Comment by vs77bb** [comment]
@nanspro Are you still working on this one? Missed you at Devcon, glad you met Kevin :)

**Comment by nanspro** [comment]
@vs77bb just arrived back to india today and now i'll finish up these pending tasks and move forward. Btw since it is an contest bounty i guess i am not blocking it for anyone, right? That was the reason i thought about doing it after devcon.

Come to ETH India this time :) I'll try for ETH Berlin too.

**Comment by sirpy** [comment]
@nanspro hey whats up? any updates?

**Pull request closed without merging**
